services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: meu_usuario
      MONGO_INITDB_ROOT_PASSWORD: minha_senha
      MONGO_INITDB_DATABASE: desafio_backend
    volumes:
      - ./data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
